---
title: "Code of Conduct"

output: 
  html_document:
   toc: true
   toc_float: true
  toc_depth: 3
---

## Code of Conduct (English)
Kawaguchi CB lab aims to provide a place where every participant can grow both mentally and scientifically through the sharing of information and communicating each other, ultimately contributing to science and society.
We, all the members of Kawaguch lab have made an effort to provide a safe, welcoming environment for every participant.

All lab members (regardless of the period) and participants of our lab seminars are required to agree to the following code of conduct. 
Organizers will enforce this code at the workplace, seminar and meeting, personal messages, and parties/meet-up related social events, no matter if they are online or in person.
We expect cooperation from every participant (including organizers, staff members, researchers, students, and any other attendees) to ensure a safe space for everybody.

Our gathering is dedicated to providing a safe environment for everyone, **regardless of gender, gender identity and expression, age, sexual orientation, physical appearance, body size, disability, medical history, race, ethnicity, religion (or lack thereof), family, technology choices and skills, scientific knowledge and beliefs**, and other characteristics.

We will eliminate **deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, unwelcome attention, and other behaviors to attack a person or group**. In addition, it is not allowed to support or agitate those offensive behaviors. 
We do not tolerate harassment of participants in any shape or form. 

Participants asked to stop any harassing behavior are expected to comply immediately. Participants violating these rules may be removed from the activity and/or blocked from future events, at the discretion of the organizers and staffs.

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact the organizer, one of our staff members you can trust, or an appropriate office staff immediately. 
We will be happy to help participants experiencing harassment to feel safe for the duration of being with us.


## 行動規範 (Japanese)
河口研究室は、科学への誠実な貢献を最終的な目標とし、情報の共有とコミュニケーションを通して科学者としても人間としても誰もが成長できる場となることを目指しています。私たちはすべての研究室メンバーにとって安全で歓迎されるような場を作ることに努めます。

河口研究室に所属するすべてのメンバー（短期・長期問わず）と、河口研究室主催のセミナーの参加者は下記の行動規範を守ることを求められます。この行動規範はオンライン・オフラインを問わず、研究室での研究活動と休憩時間、セミナーやミーティング、個人的なメッセージでのやり取り、交流会などに適用します。すべての人にとって安全な場所を提供するため、教員、スタッフ、研究員、学生を含めたすべての参加者にご協力をお願いします。

私たちは下記のような事柄や、これに限らない様々な属性を持つすべての人にとって安全な場を提供することに努めます。

- 社会的あるいは法的な性、性自認、性表現（外見の性）、性指向
- 年齢、容姿、体格、障がい、既往歴
- 人種、民族、宗教（無宗教を含む）
- 家族構成
- 技術的な習熟度、技術の選択
- 学問的立場、科学的な知識

そして下記のようなハラスメント行為をいかなる形であっても決して許容しません。

- 脅迫、つきまとい、ストーキング
- 不適切な画像、動画、録音の再生（性的な画像など）
- 発表やその他の研究活動に対する妨害行為
- 不適切な身体的接触
- 歓迎されない注目のされ方
- これらに限らない個人・集団に対する攻撃的な言動やいじめ行為とそれらの擁護

ハラスメント行為を指摘されやめるように指示された場合、直ちに従うことが求められます。ルールを守らない参加者は、研究室主宰者およびスタッフなどの判断により、活動やイベントの参加禁止などの対応をとります。
もしハラスメントを受けていると感じたり、他の誰かがハラスメントされていることに気がついた場合、研究室主宰者もしくは信頼できるスタッフや適切な部署に連絡をお願いします。
主宰者及びスタッフは、参加している誰もが安心できるようアシストさせていただきます。


## ကျင့်၀တ်စည်းမျည်း(Myanmar)  
<br>

Kawaguchi ဓာတ်ခွဲခန်းသည် ပါဝင်သူတိုင်း သတင်းအချက်အလက်မျှဝေခြင်းနှင့် အချင်းချင်းဆက်သွယ်ခြင်းတို့ဖြင့် သိပ္ပံပညာနှင့် လူ့အဖွဲ့အစည်းအတွက် အဆုံးစွန် ပါဝင်ကူညီမှုမှတစ်ဆင့် စိတ်ပိုင်းဆိုင်ရာနှင့် သိပ္ပံနည်းကျမှု နှစ်မျိုးစလုံး ဖွံ့ဖြိုးစေသည့်နေရာတစ်ခုအဖြစ် ပံ့ပိုးပေးရန် ရည်ရွယ်ပါသည်။ ကျွန်ုပ်တို့၊ Kawaguchi ဓာတ်ခွဲခန်းအဖွဲ့ဝင်များအားလုံးသည် ပါဝင်သူတိုင်းးအတွက် ဘေးကင်းလုံခြုံပြီး ဖော်ရွေသည့် ပတ်ဝန်းကျင်ကို ဖြည့်ဆည်းပေးနိုင်ရန် ကြိုးပမ်းအားထုတ်ကြပါသည်။

ဓာတ်ခွဲခန်းအဖွဲ့ဝင်များအားလုံး (အချိန်ကာလကို မခွဲခြားဘဲ) နှင့် ကျွန်ုပ်တို့ဓာတ်ခွဲခန်း၏ ဆွေးနွေးပွဲများတွင် ပါဝင်သူများသည် အောက်ပါစည်းမျည်း များကို သဘောတူရန် လိုအပ်ပါသည်။ စီစဉ်သူများသည် လုပ်ငန်းခွင်၊ ဆွေးနွေးပွဲနှင့် အစည်းအဝေးများ၊ ကိုယ်ရေးကိုယ်တာ အချက်လက်များနှင့် လူမှုရေးနှင့် ဆက်စပ်သော ပါတီများ/တွေ့ဆုံပွဲများတွင်အွန်လိုင်း မှတက်‌ရောက်သည်ဖြစ်စေ ကိုယ်တိုင်လာရောက်သည်ဖြစ်စေ လိုက်နာရန် ဤ ကျင့််၀တ် စည်းမျည်း များကို ပြဋ္ဌာန်းပါသည်။ ပါဝင်သူတိုင်း (စီစဉ်သူများ၊ ဝန်ထမ်းများ၊ သုတေသီများ၊ ကျောင်းသားများနှင့် အခြားတက်ရောက်သူများ အပါအဝင်) မှ ပူးပေါင်းဆောင်ရွက်ခြင်းကို မျှော်လင့်ပါသည်။

ကျွန်ုပ်တို့ စုဝေးမှုသည် ကျား၊ မ၊ သတ်မှတ်ချက်နှင့်ဖြစ်တည်မှု၊ အသက်၊ လိင်ပိုင်းဆက်နွယ်မှု၊ အသားအရောင်၊ ကိုယ်ခန္ဓာအရွယ်အစား၊ မသန်စွမ်းမှု၊ ဆေးဘက်ဆိုင်ရာ ရာဇဝင်၊ လူမျိုး၊ နိုင်ငံသား၊ ကိုးကွယ်မှုဘာသာတရား သို့မဟုတ် ဘာသာတရားမရှိ ၊ မိသားစု၊ နည်းပညာရွေးချယ်မှုနှင့် ကျွမ်းကျင်မှု၊ သိပ္ပံနည်းကျ ဗဟုသုတနှင့် ယုံကြည်မှုနှင့် အခြားဝိသေသလက္ခဏာများပေါ်တွင် ခွဲခြားမှုမရှိပဲ လူတိုင်းအတွက် လုံခြုံမှုရှိသော ပါတ်ဝန်းကျင်တစ်ခု ဖြစ်စေပါမည်။ 

ကျွန်ုပ်တို့သည် နှောင့်ယှက်ခြိမ်းခြာက်ခြင်း နောက်ယောင်ခံခြင်း နှောင့်ယှက်ဓာတ်ပုံရိုက်ခြင်း သို့မဟုတ် မှတ်တမ်းတင်ခြင်း ဟောပြောခြင်း သို့မဟုတ် လုပ်ဆောင်ခြင်းတို့ကို ဆက်တိုက်နှောင့်ယှက်ခြင်း ၊ မသင့်လျော်သော ရုပ်ပိုင်းဆိုင်ရာ ထိတွေ့မှု၊ အနှောင့်အယှက်ဖြစ်စေသည့် အာရုံစိုက်မှုနှင့် လူတစ်ဦးချင်းကိုလည်းကောင်း အဖွဲ့ကိုလည်းကောင်း တိုက်ခိုက်မှုများကို ဖယ်ရှားပါမည်။ ထို့အပြင် အဆိုပါ ရန်လိုနှောင့်ယှက်သည့် အပြုမူများကို ထောက်ခံခြင်း သို့မဟုတ် လှုံ့ဆော်ခြင်း တို့ကိုခွင့်မပြုပါ။ ကျွန်ုပ်တို့သည် ပါဝင်သူ များ ၏ နှောင့်ယှက် မှုကို ညှိနှိုင်း ၊ သည်းခံ မည်မဟုတ်ပါ။

ပါဝင်သူများသည် အနှောင့်အယှက်ဖြစ်စေသည့် အပြုအမူမှန်သမျှကို ရပ်တန့်ရန် တောင်းဆိုခံရပါက ချက်ချင်းလိုက်နာရမည်ဖြစ်ပါသည်။ ဤစည်းမျဥ်းစည်းကမ်းများကို ချိုးဖောက်သောပါဝင်သူများသည် ပွဲစီစဉ်သူများနှင့် ဝန်ထမ်းများ၏ ဆုံးဖြတ်ချက်အရ အစီအစဉ်မှ ဖယ်ရှားခြင်း (သို့မဟုတ်) နောင်တွင် ကျွန်ုပ်တို့ဓာတ်ခွဲခန်း၏ အစီအစဉ် များ တွင် ပါဝင် ခြင်းကို ပိတ်ပင် ပါမည်။

အကယ်၍ သင်သည် နှောင့်ယှက်ခံရပါက အခြားသူတစ်ဦးအား နှောင့်ယှက်ခံနေရသည်ကို သတိပြုမိပါက သို့မဟုတ် အခြားစိုးရိမ်မှုများရှိပါက ကျေးဇူးပြု၍ စီစဉ်သူ၊ သင်ယုံကြည်ရနိုင်သော ကျွန်ုပ်တို့၏ ဝန်ထမ်းအဖွဲ့ဝင်တစ်ဦး သို့မဟုတ် သင့်လျော်သောရုံးဝန်ထမ်းများထံ ချက်ချင်းဆက်သွယ်ပါ။ နှောင့်ယှက်မှုကြုံနေရသည့် ပါဝင်သူများအား ကျွန်ုပ်တို့နှင့်အတူ ရှိနေစဉ်ကာလအတွင်း ဘေးကင်းကြောင်း ခံစားနိုင်ရန် ကူညီပေးပါမည်။

(Translated by TT)

*** 

- This work is based on [DroidKaigi Code of Conduct](https://portal.droidkaigi.jp/en/about/code-of-conduct).
- Other sources: [http://2012.jsconf.us/#/about](http://2012.jsconf.us/#/about) & The Ada Initiative (Original). [Droidcon NYC Code of Conduct](https://www.nyc.droidcon.com/code-of-conduct).
- This work is licensed under a [Creative Commons Attribution 3.0 Unported License](https://creativecommons.org/licenses/by/3.0/deed.en_US).

*** 

## Additional rules for lab members
To be a professional in science,

- Keeping track of your work and summarize it for others and the future yourself
- Following safety protocols and lab guidelines
- Cleaning up your work space
- Taking responsibility and holding yourself accountable for your words and actions (in both experimental and no-experimental areas)
- Being respectful to others (resource, time, and personal boundaries)
- Trying to make question during every science discussion


## Reference

- We also follow the policies issued by the affiliation.
  - [Harassment Policy at Kyoto University](https://www.kyoto-u.ac.jp/en/about/human-rights/harassment-policy-at-kyoto-university)
  - [京都大学におけるハラスメントの防止と対応について](https://www.kyoto-u.ac.jp/ja/about/foundation/human-rights/harassment)
