---
title: "Publication"

output: 
  html_document:
   toc: true
   toc_float: true
  toc_depth: 3
---

### Journal article
* "Concentration-dependent formation of intersegment interactions in viral droplets of influenza A virus infected cells." Takizawa N, Higashi K, <u>**Kawaguchi RK**</u>, Gotoh Y, Hayashi T, Kurokawa K. (accepted)
* "Multiple human enhancer RNAs contain long translated open reading frames." Vlasov PA, Ogami K, Valenzuela E, <u>**Kawaguchi RK**</u>, Jovanovic M, Manley JL. (accepted)
* "A feedback amplifier circuit with Notch and E2A orchestrates T-cell fate and suppresses the innate lymphoid cell lineages during thymic ontogeny." 
Miyazaki K, Horie K, Watanabe H, Hidaka R, Hayashi R, Hayatsu N, Fujiwara K, Kuwata R, Uehata T, Ochi Y, Takenaka M, <u>**Kawaguchi RK**</u>, Ikuta K, Takeuchi O, Ogawa S, Hozumi K, Holländer GA, Kondoh G, Akiyama T, Miyazaki M.*Genes Dev*, gad.352111.124.abstract, 2025. [[link]](https://genesdev.cshlp.org/content/early/2025/02/04/gad.352111.124.abstract)
* "RNAelem: An Algorithm for Discovering Sequence-Structure Motifs in RNA Bound by RNA-Binding Proteins." Miyake H, <u>Kawaguchi RK</u>, Kiryu H. *Bioinformatics Advances*, vbae144, 2024.
[[link]](https://doi.org/10.1093/bioadv/vbae144)
* "The transcriptional legacy of developmental stochasticity." Ballouz S†, <u>**Kawaguchi RK**†</u>, Pena MT, Fischer S, Crow M, French L, Knight FM, Adams LB, Gillis J. *Nature Communications*, 14, 7226, 2023. [[link]](https://www.nature.com/articles/s41467-023-43024-5) [[bioRxiv]](https://www.biorxiv.org/content/10.1101/2019.12.11.873265v1)
* "Comprehensive in virio structure probing analysis of the influenza A virus identifies functional RNA structures involved in viral genome replication." Takizawa N\*, <u>**Kawaguchi RK**</u>. *Computational and Structural Biotechnology Journal*, 21:5259-72, 2023. [[link]](https://www.sciencedirect.com/science/article/pii/S2001037023003926)[[bioRxiv]](https://www.biorxiv.org/content/10.1101/2020.03.05.975870v2)
* "Learning single-cell chromatin accessibility profiles using meta-analytic marker genes." <u>**Kawaguchi RK**</u>, Tang Z, Fischer S, Rajesh C, Tripathy R, Koo PK, Gillis J. *Briefings in Bioinformatics*, bbac541, 2022. [[link]](https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bbac541/6957249) [[bioRxiv]](https://www.biorxiv.org/content/10.1101/2021.04.01.438068v2)
* "Prevalent and dynamic binding of the cell cycle checkpoint kinase Rad53 to gene promoters." Sheu YJ, <u>**Kawaguchi RK**</u>, Gillis J, Stillman B. *eLife*, 11:e84320, 2022. [[link]](https://elifesciences.org/articles/84320) [[bioRxiv]](https://www.biorxiv.org/content/10.1101/2021.05.23.445333v3)

* The list of older papers is available [here](https://scholar.google.com/citations?user=BLtM6hoAAAAJ).


### Review
* <u>**Kawaguchi RK**</u> and Kiryu H. RNA Secondary Structure Alteration Caused by Single Nucleotide Variants. In: RNA Structure Prediction. Methods in Molecular Biology, vol 2586. Humana, New York, 2023. [[link]](https://doi.org/10.1007/978-1-0716-2768-6_7)
* <u>**Kawaguchi RK**</u> and Kiryu H. Genome-Wide RNA Secondary Structure Prediction. In: RNA Structure Prediction. Methods in Molecular Biology, vol 2586. Humana, New York, 2023. [[link]](https://doi.org/10.1007/978-1-0716-2768-6_3)

### Book
* RNA structure prediction Edited by <u>**Kawaguchi RK**</u> and Iwakiri J. Methods in molecular biology, Humana New York, 2023. [[link]](https://doi.org/10.1007/978-1-0716-2768-6)
* The list goes on [[here]](https://researchmap.jp/cawatchm).

### Presentation
* List of presentations is available [here](https://sites.google.com/site/cawatchm/presentation)

